store/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import regiser_view

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', regiser_view, name='register'),
]

store/api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'products', views.ProductViewSet)
router.register(r'orders', views.OrderViewSet)


app_name = 'api_1'


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

store/online_store/urls.py
from django.urls import path

from .views import (
    IndexProductView,
    ViewProductView,
    CreateProductView,
    UpdateProductView,
    DeleteProductView,
    AddToCartView,
    IndexCartView,
    DeleteCartView,
    CreateOrderView,
    UserOrderView,
    StatView,
)
# app_name = 'store'
urlpatterns = [
    path('', IndexProductView.as_view(), name='product_list'),  # URL для отображения списка productov
    path('<category>', IndexProductView.as_view(), name='product_category_list'),  # URL для отображения списка productov
    path('product/<int:pk>/', ViewProductView.as_view(), name = 'product_view'),
    path('product/create', CreateProductView.as_view(), name = 'product_create'),
    path('product/<int:pk>/update', UpdateProductView.as_view(), name = 'product_update'),
    path('product/<int:pk>/delete', DeleteProductView.as_view(), name = 'product_delete'),
    path('basket/<int:pk>/add',AddToCartView.as_view(), name="add_to_cart"),
    path('basket/', IndexCartView.as_view(), name='cart_list'),
    path('basket/<int:pk>/delete', DeleteCartView.as_view(), name='cart-delete'),
    path('order/new',CreateOrderView.as_view(), name='order_create'),
    # path('user/order/new',CreateUserOrderView.as_view(), name='user_order_create'),
    path('user/orders',UserOrderView.as_view(), name='user_order_list'),
    path('stat/',StatView.as_view(), name='stat'),

]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('online_store.urls')),  # подключаем URLs из приложения online-store
    path('accounts/', include('accounts.urls')),
    path('api_1/api/', include('api.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/online_store/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
CATEGORY_CHOICES=[
    ('breakfast','завтрак'),
    ('first meal','первые блюда'),
    ('second courses','вторые блюда'),
    ('drinks','напитки '),
    ('other','разное'),
]

class Product(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name="Наименование")
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name="Описание")
    category = models.CharField(max_length=32, null=False, blank=False, choices=CATEGORY_CHOICES, default='other')
    remainder = models.IntegerField(validators=[MinValueValidator(0)])
    price = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(0)])

    class Meta:
        db_table = 'products'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f'{self.id}. {self.name}: {self.price}'

class CartProduct(models.Model):
    product = models.ForeignKey('online_store.Product', on_delete=models.CASCADE, related_name='cart_products', verbose_name='продукт')
    qty = models.IntegerField(validators=[MinValueValidator(0)])

    class Meta:
        verbose_name="товар в корзине"
        verbose_name_plural="товары в корзине"

    def summa(self):
        return self.product.price*self.qty

    def get_all(self):
        summa=0
        for obj in CartProduct.objects.all():
            summa+=obj.summa()

        return summa

class Order(models.Model):
    name = models.CharField(max_length=128  )
    tel = models.CharField(max_length=128)
    address = models.CharField(max_length=256 )
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True, related_name='order' )
    created_at=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='Заказчик'
        verbose_name_plural='Заказчики'

    def get_total(self):
        total=0
        ordered_products = ProductOrder.objects.filter(order = self)
        for ordered_product in ordered_products:
            total+=ordered_product.summa()
        return total

    def __str__(self):
        return f'{self.name}:{self.user}'

class ProductOrder(models.Model):
    product = models.ForeignKey('online_store.Product', on_delete=models.CASCADE, related_name='orders')
    order = models.ForeignKey('online_store.Order', on_delete=models.CASCADE, related_name='products')
    qty = models.IntegerField(validators=[MinValueValidator(0)])

    class Meta:
        verbose_name='Заказ'
        verbose_name_plural='Заказы'

    def summa(self):
        return self.product.price*self.qty


    def __str__(self):
        return f'{self.order.name}:{self.product.name}-{self.qty}'

store/online_store/forms.py
from django import forms

from .models import Product, Order
CATEGORY_CHOICES=[
    ('breakfast','завтрак'),
    ('first meal','первые блюда'),
    ('second courses','вторые блюда'),
    ('drinks','напитки '),
    ('other','разное'),
]

class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description', 'category', 'price', 'remainder')


class ProductSearchForm(forms.Form):
    name = forms.CharField(max_length=100)

class SearchForm(forms.Form):
    search_value = forms.CharField(max_length=100, required=False, label='Найти')

class OrderForm(forms.ModelForm):
    class Meta:
        model=Order
        fields=('name', 'tel', 'address')

store/online_store/views.py
from copy import deepcopy

from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from django.utils.http import urlencode
from django.contrib import messages
from datetime import datetime, timedelta

from .forms import ProductSearchForm, ProductForm, SearchForm, OrderForm
from .models import Product, CATEGORY_CHOICES, CartProduct, ProductOrder, Order
# Create your views here.

class StatMixin:
    request = None

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        self.set_common_stat()
        self.set_page_time()
        return super().dispatch(request, *args, **kwargs)

    def set_common_stat(self):
        print(self.request.path)
        if 'stat' not in self.request.session:
            self.request.session['stat'] = {}

        stat = self.request.session.get('stat', {})
        if 'common_start_time' not in stat:
            stat['common_start_time'] = datetime.now().strftime('%d/%m/%y %H:%M:%S')
        if 'common_click_count' not in stat:
            stat['common_click_count'] = 1
        else:
            stat['common_click_count'] += 1
        self.request.session['stat'] = stat


    def set_page_time(self):
        if 'stat' not in self.request.session:
            self.request.session['stat'] = {}
        stat = self.request.session.get('stat', {})
        if 'page' not in stat.keys():
            stat['page']={}
        page=stat['page']
        if self.request.path not in page:
            page[self.request.path]={}
            page[self.request.path]['time'] = 0
            page[self.request.path]['click'] = 1
        else:
            page[self.request.path]['click'] +=1

        if 'new' in stat:
            old_time =page[stat['new']['path']]['time']
            time = (datetime.now() - datetime.strptime(stat['new']['start'], '%d/%m/%y %H:%M:%S')).seconds
            new_time = int(old_time) + time
            page[stat['new']['path']]['time'] = new_time
        else:
            stat['new']={}
        stat['new']['start'] = datetime.now().strftime('%d/%m/%y %H:%M:%S')
        stat['new']['path'] = self.request.path

        stat['page']=page
        self.request.session['stat'] = stat


class StatView(StatMixin, View):
    def get(self, request, *args, **kwargs):
        common_time = 0
        clicks=0
        if 'stat' not in self.request.session:
            self.request.session['stat'] = {}
        stat = self.request.session.get('stat', {})
        stat = deepcopy(stat)

        if 'common_start_time' in stat:
            start = datetime.strptime(stat['common_start_time'], '%d/%m/%y %H:%M:%S')
            end = datetime.now()
            common_time = str(end - start)
            clicks = stat['common_click_count']

        if 'page' not in stat:
            stat['page']={}
        pages=stat['page']
        print(f'pages={pages}')
        for key,values in pages.items():
            pages[key]['time'] = datetime.fromtimestamp(int(pages[key]['time'])).strftime("%H:%M:%S")

        if '/stat/' in pages:
            pages.pop('/stat/')

        print(f'pages={pages}')

        return render(request, 'stat.html', context={'time':common_time, 'cls':clicks, 'pages':pages})

class IndexProductView(StatMixin, ListView):
    template_name = 'product/index.html'
    model = Product
    context_object_name = 'products'
    ordering = ('category', 'name')
    paginate_by = 5


    def get(self,request, **kwargs):
        # self.set_time(request)
        self.form = SearchForm(request.GET)
        self.search_data = self.get_search_data()
        # print(f'session={self.request.session.get("products",{})}')
        print(f'session={self.request.session.get("stat",{})}')
        return super().get(request, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.kwargs.get('category'):
            queryset = queryset.filter(category=self.kwargs.get('category'))
        queryset = queryset.exclude(remainder=0)

        if self.search_data:
            queryset = queryset.filter(
                Q(name__icontains=self.search_data) |
                Q(description__icontains=self.search_data))
        return queryset

    def get_search_data(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search_value']
        return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = CATEGORY_CHOICES
        context['search_form'] = self.form


        if self.search_data:
            context['query'] = urlencode({'search_value': self.search_data})
        return context

class ViewProductView(StatMixin, DetailView):
    template_name = 'product/view.html'
    queryset = Product.objects.exclude(remainder=0)
    context_object_name = 'product'

class CreateProductView(PermissionRequiredMixin, StatMixin, CreateView):
    permission_required = ['online_store.add_product']
    template_name = 'product/create.html'
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('product_view', kwargs={'pk': self.object.pk})

class UpdateProductView(PermissionRequiredMixin,StatMixin, UpdateView):
    permission_required = ['online_store.change_product']
    form_class = ProductForm
    model = Product
    template_name = 'product/update.html'
    context_object_name = 'product'

    def get_success_url(self):
        return reverse('product_view', kwargs={'pk':self.object.pk})

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.exclude(remainder=0)
        return queryset

class DeleteProductView(PermissionRequiredMixin,StatMixin,  DeleteView):
    permission_required = ['online_store.delete_product']
    template_name = 'product/delete.html'
    model = Product
    context_object_name = 'product'
    success_url = reverse_lazy('product_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.exclude(remainder=0)
        return queryset


class AddToCartView(View):
    def get(self, request, *args, **kwargs):
        product = get_object_or_404(Product,id=kwargs.get('pk'))
        try:
            cart_product = CartProduct.objects.get(product=product)
            if product.remainder>0:
                cart_product.qty+=1
                product.remainder-=1
                product.save()
                cart_product.save()
                if 'products' not in request.session:
                    request.session['products'] = {}
                products = request.session.get('products', {})
                products[product.name] = cart_product.qty
                request.session['products'] = products
                messages.success(self.request, f'{product.name} : 1 item added')
            else:
                messages.error(self.request, f'Cannot add {product.name}')
        except CartProduct.DoesNotExist:
            if product.remainder!=0:
                cart_product=CartProduct.objects.create(product=product, qty=1)
                product.remainder -= 1
                product.save()
                if 'products' not in request.session:
                    request.session['products'] = {}
                products = request.session.get('products', {})
                products[product.name] = cart_product.qty
                request.session['products'] = products
                messages.success(self.request, f'{product.name} : 1 item added')
            else:
                messages.error(self.request, f'Cannot add {product.name}')


        return redirect('cart_list')

class IndexCartView(StatMixin, ListView):
    template_name = 'basket/index.html'
    model = CartProduct
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form']=OrderForm()

        return context


class DeleteCartView(DeleteView):
    model = CartProduct
    success_url = reverse_lazy('cart_list')
    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        product = Product.objects.get(id=self.object.product.id)
        product.remainder+=self.object.qty
        product.save()
        products = request.session.get('products', {})
        products[product.name] = None
        request.session['products'] = products
        self.request.session['products'][product.name] = None
        messages.warning(self.request, f'{product.name} deleted')
        self.object.delete()

        return HttpResponseRedirect(success_url)

class CreateOrderView(View):
    def post(self, request, *args, **kwargs):
        form = OrderForm(data=request.POST)
        if form.is_valid():
            order = Order.objects.create(
                name=form.cleaned_data.get('name'),
                tel=form.cleaned_data.get('tel'),
                address=form.cleaned_data.get('address')
            )
            if request.user.is_authenticated:
                order.user=request.user
                order.save()

            for product in CartProduct.objects.all():
                product_order=ProductOrder.objects.create(order=order, product=product.product, qty=product.qty)
                product_order.save()

            CartProduct.objects.all().delete()
            return redirect('product_list')
        else:
            print(form.errors)
            print('errors')
            return redirect('cart_list')

store/online_store/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Base title {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/android-icon-36x36.png' %}">
</head>
<body>
    <div class="container mt-1 mb-5">
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url "product_list" %}">Главная</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url "cart_list" %}">Корзина</a>
      </li>
      {% if user.is_authenticated and perms.online_store.add_product %}
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url "product_create" %}">Новая</a>
      </li>
      {% endif %}
        {% block nav %}
        {% endblock nav %}
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url "accounts:logout" %}?next={{ request.get_full_path }}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url "accounts:login" %}?next={% if request.GET.next %}{{ request.GET.next }}{% else %}{{ request.get_full_path }}{% endif %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url "accounts:register" %}?next={% if request.GET.next %}{{ request.GET.next }}{% else %}{{ request.get_full_path }}{% endif %}">Register</a>
            </li>
        {% endif %}
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url "user_order_list" %}">Заказы</a>
            </li>
        {% endif %}
        <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'stat' %}">Stat</a>
        </li>
    </ul>
        <h2>{% block header-text %}{% endblock header-text %}</h2>
        {% block content %} {% endblock content %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>

</body>
</html>

store/online_store/templates/index.html
{% extends 'base.html' %}
{% block title %} Главная страница {% endblock title %}
{% block header-text %} Список товаров {% endblock header-text %}
{% block content %}
        <ul class="list-group list-group-flush">
        <h4>Категории</h4>
        {% for category, display_category in categories %}
          <li class="list-group-item"><a class="nav-link active" aria-current="page" href="{% url "product_category_list" category%}">{{ display_category }}</a></li>
        {% endfor %}
        </ul>

    {% include 'product_list.html' with product_list=products %}

{% endblock content %}

store/online_store/templates/product_categories.html
{% extends 'base.html' %}
{% block title %} Страница категории{% endblock title %}
{% block header-text %} Список товаров {% endblock header-text %}
{% block content %}
    {% include 'product_list.html' with product_list=products %}
{% endblock content %}

store/online_store/templates/product_create.html
{% extends 'base.html' %}
{% block title %} Страница создания нового продукта {% endblock title %}
{% block header-text %} Создать продукт {% endblock header-text %}
{% block content %}
   <form action="{% url 'product_create'  %}" method="POST">
        {% include 'forms.html' with button_text="Создать" %}
    </form>
{% endblock content %}

store/online_store/templates/product_delete.html
{% extends 'base.html' %}

{% block title %} Delete {% endblock title %}
{% block content %}
{% load static %}
    <div class="container text-center">
        <h3 class="mt-4 mb-4">Вы действительно хотите удалить продукт  {{ product.name }}?</h3>
        <form action="{% url 'product_delete' product.id%}" method="post">
            {% csrf_token %}
            <input type="submit" name="action" value="Нет"  class="btn btn-outline-info"  />
            <input type="submit" name="action" value="Да" class="btn btn-outline-danger"/>
        </form>
    </div>
{% endblock content %}

store/online_store/templates/product_list.html
<form action="{% url 'product_list' %}" method="POST">
    {% include 'forms.html' with button_text="Искать" %}
</form>
    {% for product in product_list %}
            <div class="card text-center ">
              <div class="card-header text-capitalize ">
                  {{ product.get_category_display }}
              </div>
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <a href="{% url 'product_view' product.id %}" class="btn btn-outline-success">>Детальный просмотр</a>
              </div>
              <div class="text-primary fs-5 mb-3">
                {{ product.price }}
              </div>
            </div>
    {% endfor %}

store/online_store/templates/product_update.html
{% extends 'base.html' %}
{% block title %} Страница изменения продукта {% endblock title %}
{% block header-text %} Изменить продукт {% endblock header-text %}
{% block content %}
   <form action="{% url 'product_update' product.pk %}" method="POST">
        {% include 'forms.html' with button_text="Сохранить изменения" %}
    </form>
{% endblock content %}

store/online_store/templates/product_view.html
{% extends 'base.html' %}
{% block title %} Страница продукта {% endblock title %}
{% block header-text %} Детальный просмотр товара {% endblock header-text %}
{% block nav %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url "product_update" product.pk %}">Редактировать</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url "product_delete" product.pk %}">Удалить</a>
    </li>
{% endblock nav %}
{% block content %}
    <div class="card text-center">
      <div class="card-header text-info">
        Категория: {{ product.get_category_display}}
      </div>
      <div class="card-body">
        <h5 class="card-title">Название: {{ product.name }}</h5>
        <p class="card-text">Описание: {{ product.description}}</p>
        <p class="text-primary mt-2 mb-2"> Цена: {{ product.price }}</p>
      </div>
      <div class="card-footer text-info">
        Остаток: {{ product.remainder }}
      </div>
    </div>


{% endblock content %}

store/online_store/templates/stat.html
{% extends 'base.html' %}

{% block content %}
    <h4>Время проведенное на сайте: {{ time }}</h4>
    <h4>Количество кликов: {{ cls }} </h4>
    <p>статистика страницы stat учитывается при подсчете общих данных, но отдельно не выводится,
    потомучто логика работает таким образом что актуальные значения у всех кроме последний страницы
    куда мы зашли, так как для нее пока невозможно определить время проведенное в ней</p>

    {% for page, value in pages.items %}
        <h5>{{ page }}:</h5>
        {% for key, item in value.items %}
        <p>{{ key }}: {{ item }}</p>
        {% endfor %}
        <hr>
    {% endfor %}
{% endblock content %}